Vresh\TwilioBundle\Entity\TelephoneNumber:
    type: entity
    table: twilio__message
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        cli:
            type: string
            length: 15
            nullable: false
        countryCode:
            type: string
            length: 2
            nullable: true
        createdAt:
            type: datetime
            unsigned: false
            nullable: false
        updatedAt:
            type: datetime
            unsigned: false
            nullable: true
        enabled:
            type: boolean
            required: false
    manyToOne:
        telephoneNumber:
            targetEntity: TelephoneNumber
            inversedBy: messages

    lifecycleCallbacks:
        prePersist: [setCreatedValue,setUpdatedValue]
        preUpdate: [setUpdatedValue]
