Vresh\TwilioBundle\Entity\Message:
    type: entity
    table: twilio__message
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        recipient:
            type: string
            length: 15
            nullable: false
        content:
            type: string
            length: 255
            nullable: false
        vendorReference:
            type: string
            length: 225
            nullable: true
        createdAt:
            type: datetime
            unsigned: false
            nullable: false
        updatedAt:
            type: datetime
            unsigned: false
            nullable: true
    manyToOne:
        telephoneNumber:
            targetEntity: TelephoneNumber
            inversedBy: messages

    lifecycleCallbacks:
        prePersist: [setCreatedValue,setUpdatedValue]
        preUpdate: [setUpdatedValue]
