services:
    twilio.admin.telephoneNumber:
        class: Vresh\TwilioBundle\Admin\TelephoneNumberAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Texts", label: "Telephone Numbers" }
        arguments:
            - ~
            - Vresh\TwilioBundle\Entity\TelephoneNumber
            - ~

    twilio.admin.client:
        class: Vresh\TwilioBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Texts", label: "Messages" }
        arguments:
            - ~
            - Vresh\TwilioBundle\Entity\Message
            - ~
