parameters:
    twilio.class: Vresh\TwilioBundle\Service\TwilioWrapper

services:
    twilio.api:
        class: %twilio.class%

    twilio.handler:
        class: Vresh\TwilioBundle\Service\TwilioHandler
        arguments:
            - @twilio.api
            - @doctrine.orm.entity_manager
